/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    application
    `maven-publish`
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

apply(plugin = "com.github.johnrengelman.shadow")

repositories {
    mavenLocal()
    gradlePluginPortal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.google.code.gson:gson:2.9.0")
    implementation("com.formdev:flatlaf:2.2")
    implementation("com.intellij:forms_rt:7.0.3")
}

application {
    mainClass.set("App")
}

tasks.jar {
    manifest {
        exclude("META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA", "META-INF/*.MF")
        attributes(
            "Implementation-Title" to "Gradle",
            "Main-Class" to "App",
        )
    }
}

group = "serhiihryhorenko"
version = "1.0-beta"
description = "modelComp2"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
